
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(1001, 'Tans', 'Allabad', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(1002, 'Dhwani', 'Montreal', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(1003, 'Sahaj', 'New York', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(1004, 'Neeru', 'Mumbai', sysdate());